language: java
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdist
script:
  - mvn test -B
  - mvn javadoc:javadoc -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
notifications:
  slack:
    rooms:
      secure: "TiU8LsCX574PLWYyADKmCjalNBIn+cSGu5/4tlOjIHtPz4JceoIlvBmOUcYbrm0SF3rGL2dvWHA/5MH+RpfHqjMyUyWXnNtDZp9tOIWPxnv071W9vRykezyaMMLf8T0C7Gqizk3IEvvQjCFX2oEcoJ3nWATrkoAoswmRFNe4idA="
